volumes:
  sqlserverdata:
networks:
  backend:
    name: concert-api-net-backend
  frontend:
    name: concert-api-net-frontend
services:
  database:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password!
      - MSSQL_PID=Evaluation
    image: mcr.microsoft.com/mssql/server:2025-latest
    volumes:
     - sqlserverdata:/var/opt/mssql
    ports:
     - "1433:1433"
    networks:
      - backend
  api:
    image: concert-app-api-img:1
    build:
      tags:
        - concert-app-api-img:1
      context: ./ConcertApi
      dockerfile: ./dockerfile
    ports:
      - "5205:5205"
    networks:
      - backend
      - frontend
    depends_on:
      - database