networks:
  backend:
    name: concert-api-net-backend
  frontend:
    name: concert-api-net-frontend
services:
  database:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password!
      - MSSQL_PID=Evaluation
    container_name: concert-app-db
    hostname: sql-db
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports:
     - "1433:1433"
    expose:
      - 1433
    networks:
      - backend
  api:
    container_name: concert-app-api
    image: concert-app-api-img:1
    hostname: concert-api
    build:
      tags:
        - concert-app-api-img:1
      context: ./ConcertApi
      dockerfile: ./dockerfile
    ports:
      - "5205:5205"
    expose:
      - 5205
    networks:
      - backend
      - frontend
    depends_on:
      - database